### ISSUE TITLE
difference between parallelised version is of khmer

### ISSUE THREAD

**Issue by roblanf** [adamjorr/zypy#16]
In clean_reads.sh, it looks to me like both lines 94 and 97 are parallelised, but in different ways.

94 just does whatever khmer does for multithreading. 

97 uses ```parallel```. 

Question: do you think there's much difference?

If there isn't, I suggest we just stick with line 94 and delete 97, since 94 is clearer to read. 

Either way, can you comment out 97 for now, since as it is the script will try and do both.

**Comment by adamjorr** [comment]
The comments are misleading, sorry. The two lines do different things; 94 builds a graph and 97 filters it using whatever level of coverage we specify. The operation in 94 is parallelized in khmer, but the operation in 97 is not, which is why we have to use parallel. The command is ugly though, so I will add some things to make it more readable. I think I will need to do some work to make it more generalized as well, as you note in #15
